#!/bin/sh

ISCALLER=$1
shift

MODE=$1
shift

FILENAME=".nice$ISCALLER.cre"

if [ "$MODE" = "publish" ]; then
  cat > $FILENAME
fi

if [ "$MODE" = "unpublish" ]; then
  rm -f $FILENAME
fi

if [ "$MODE" = "lookup" ]; then
  if [ $ISCALLER = "1" ]; then 
    FILENAME=".nice0.cre"
  else
    FILENAME=".nice1.cre"
  fi

  while [ ! -f "$FILENAME" ]; do
    #inotifywait -q -t 100 -e create . > /dev/null
    sleep 1
  done
  cat $FILENAME
fi
